targets:
  $default:
    builders:
      drift_dev:
        options:
          store_date_time_values_as_text: true
          named_parameters: true
          apply_converters_on_variables: true
          override_hash_and_equals_in_result_sets: true
          use_data_class_name_for_companions: true
          mutable_classes: false
          generate_connect_constructor: false
          write_to_columns_mixins: false
