name: moneyt_pfm
description: "Personal Finance Manager"
publish_to: 'none'
version: 0.2.0+6

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.9
  drift: ^2.22.1
  sqlite3_flutter_libs: ^0.5.27
  path: ^1.9.0
  path_provider: ^2.1.5
  get_it: ^8.0.3
  provider: ^6.1.2
  shared_preferences: ^2.3.4
  google_sign_in: ^6.2.2
  firebase_core: ^3.9.0
  firebase_auth: ^5.3.4
  cloud_firestore: ^5.6.0
  url_launcher: ^6.2.2
  flutter_expandable_fab: ^2.3.0
  screenshot: ^3.0.0
  share_plus: ^10.1.3
  file_picker: ^8.1.7
  permission_handler: ^11.3.1
  package_info_plus: ^8.1.2
  flutter_contacts: ^1.1.9+2
  injectable: ^2.5.0
  firebase_analytics: ^11.4.0
  equatable: ^2.0.7
  filesize: ^2.0.1
  slang: ^4.7.2
  slang_flutter: ^4.7.0
  intl: ^0.20.2
  confetti: ^0.7.0  # Para efectos de confetti en completion page
  superwallkit_flutter: ^2.3.5
  table_calendar: ^3.2.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  drift_dev: ^2.22.1
  build_runner: ^2.4.13
  flutter_launcher_icons: ^0.14.2

flutter:
  uses-material-design: true
