class IconToEmojiMapper {
  static String getEmoji(String iconName) {
    const map = {
      'fastfood': '🍔',
      'restaurant': '🍽️',
      'local_dining': '🍱',
      'directions_car': '🚗',
      'commute': '🚌',
      'local_taxi': '🚕',
      'shopping_cart': '🛍️',
      'shopping_bag': '👜',
      'local_grocery_store': '🛒',
      'movie': '🎬',
      'theaters': '🎭',
      'health_and_safety': '💊',
      'local_hospital': '🏥',
      'medical_services': '🩺',
      'home': '🏠',
      'house': '🏡',
      'flight': '✈️',
      'airplanemode_active': '🛫',
      'school': '🎓',
      'menu_book': '📚',
      'fitness_center': '🏋️‍♂️',
      'sports_gymnastics': '🤸',
      'pets': '🐾',
      'child_care': '👶',
      'work': '💼',
      'business_center': '🏢',
      'receipt': '🧾',
      'payment': '💳',
      'attach_money': '💵',
      'money': '💸',
      'account_balance': '🏦',
      'savings': '🐷',
      'electrical_services': '⚡',
      'water_drop': '💧',
      'wifi': '📶',
      'phone_iphone': '📱',
      'computer': '💻',
      'gamepad': '🎮',
      'stroller': '🍼',
      'celebration': '🎉',
      'cake': '🎂',
      'smoking_rooms': '🚬',
      'liquor': '🍷',
      'local_bar': '🍺',
      'local_cafe': '☕',
      'emoji_food_beverage': '🍵',
      'park': '🌳',
      'forest': '🌲',
      'pool': '🏊‍♂️',
      'beach_access': '🏖️',
    };

    return map[iconName] ?? '🏷️';
  }
}
