// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDC8kvAGt2D2IdOlMhm8e_boMe9MwKLZ5o',
    appId: '1:348870461211:web:d9691b9136fb38e152f5be',
    messagingSenderId: '348870461211',
    projectId: 'moneyt-io',
    authDomain: 'moneyt-io.firebaseapp.com',
    storageBucket: 'moneyt-io.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCk_NelVPUHfhjKL-5ZEu_gxsq5i9W-CZU',
    appId: '1:348870461211:android:64b4879259a752fb52f5be',
    messagingSenderId: '348870461211',
    projectId: 'moneyt-io',
    storageBucket: 'moneyt-io.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBca-c1qGm34ZdOfrPSINi2guJa3A7MXKo',
    appId: '1:348870461211:ios:218ac6297440bc4d52f5be',
    messagingSenderId: '348870461211',
    projectId: 'moneyt-io',
    storageBucket: 'moneyt-io.firebasestorage.app',
    androidClientId: '348870461211-me0j4c88agej3rjj4vlc9b1c72p19aot.apps.googleusercontent.com',
    iosClientId: '348870461211-3issktspt19hdip90j1p3k4fsdmr457q.apps.googleusercontent.com',
    iosBundleId: 'io.moneyt.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBca-c1qGm34ZdOfrPSINi2guJa3A7MXKo',
    appId: '1:348870461211:ios:218ac6297440bc4d52f5be',
    messagingSenderId: '348870461211',
    projectId: 'moneyt-io',
    storageBucket: 'moneyt-io.firebasestorage.app',
    androidClientId: '348870461211-me0j4c88agej3rjj4vlc9b1c72p19aot.apps.googleusercontent.com',
    iosClientId: '348870461211-3issktspt19hdip90j1p3k4fsdmr457q.apps.googleusercontent.com',
    iosBundleId: 'io.moneyt.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDC8kvAGt2D2IdOlMhm8e_boMe9MwKLZ5o',
    appId: '1:348870461211:web:0b5f3c6fc0a94ead52f5be',
    messagingSenderId: '348870461211',
    projectId: 'moneyt-io',
    authDomain: 'moneyt-io.firebaseapp.com',
    storageBucket: 'moneyt-io.firebasestorage.app',
  );
}
